export const User=[
{
    "id": 1,
    "firstName": "Emily",
    "status": "New",
    "email": "emily.johnson@x.dummyjson.com",
      "phone": "+81 965-431-3024",
      "Companyname": "Dooley, Kozey and Cronin",
},
{
    "id": 2,
    "firstName": "Michael",
    "status": "Contacted",
    "email": "emily.johnson@x.dummyjson.com",
      "phone": "+81 965-431-3024",
      "Companyname": "Dooley, Kozey and Cronin",
},
{
    "id": 3,
    "firstName": "Sophia",
    "status": "IN Progress",
    "email": "emily.johnson@x.dummyjson.com",
      "phone": "+81 965-431-3024",
      "Companyname": "Dooley, Kozey and Cronin",
},
{
    "id": 4,
    "firstName": "Sophia",
    "status": "Proposed",
    "email": "emily.johnson@x.dummyjson.com",
      "phone": "+81 965-431-3024",
      "Companyname": "Dooley, Kozey and Cronin",
},
{
    "id": 5,
    "firstName": "Sophia",
    "status": "Negotiated",
    "email": "emily.johnson@x.dummyjson.com",
      "phone": "+81 965-431-3024",
      "Companyname": "Dooley, Kozey and Cronin",
},
{
    "id": 6,
    "firstName": "Sophia",
    "status": "Deal",
    "email": "emily.johnson@x.dummyjson.com",
      "phone": "+81 965-431-3024",
      "Companyname": "Dooley, Kozey and Cronin",
},
{
    "id": 7,
    "firstName": "Sophia",
    "status": "Closed",
    "email": "emily.johnson@x.dummyjson.com",
      "phone": "+81 965-431-3024",
      "Companyname": "Dooley, Kozey and Cronin",
},
]